on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_webfiles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check webfiles
        run: ls -la

  check_html_files:
    needs: check_webfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check index.html
        run: test -f about.html

  check_css_files:
    needs: check_html_files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check CSS files
        run: test -f style.css

  website_check_successful:
    needs: check_css_files
    runs-on: ubuntu-latest
    steps:
      - name: Website check successful
        run: echo "Website check successful"